version: '3'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - furya-data:/var/lib/postgresql/data/ # persist data even if container shuts down  
    ports:
      - "5432:5432"
  prices-postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - prices-data:/var/lib/postgresql/data/ # persist data even if container shuts down  
    ports:
      - "5433:5433"

volumes:
  furya-data: # named volumes can be managed easier using docker-compose
  prices-data: 
